/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assign.h"
#include<unistd.h>
#include<stdio.h>
#include<time.h>

void
assign_1(char *host)
{
	CLIENT *clnt;		
	

#ifndef	DEBUG
	
#endif	/* DEBUG */
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
int main (int argc, char *argv[])
{
	//All Variables
	char *host;
	int  *result_1;
	char *first_1_arg;
	ques  *result_2;
	int get_ques_1_arg;
	int  *result_3;
	ans  check_ans_1_arg;
	int  *result_4;
	int  ask_score_1_arg;
	int  *result_5;
	board  *result_6;
	char *get_board_1_arg;
	int  ask_rank_1_arg;
	void  *result_7;
	int  exit_1_arg;
	int crash = 0;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char name[20];
	CLIENT *clnt;
	clnt = clnt_create (host, ASSIGN, ASSIGN_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	int c_id,lques;
	if( access( "ClientId.txt", F_OK ) != -1 ) {
		FILE *fp = fopen("ClientId.txt","r");
		fscanf(fp,"%d %d %s",&c_id,&lques,name);	
		crash = 1;
		fclose(fp);
	} else {
	    	//FILE *fpw = fopen("ClientId.txt","w");
		//fprintf(fpw,"%d",*result_1);
		//fclose(fpw);
		c_id = -1;
	}
	if(crash == 0)
		printf("\t\t\tWelcome To The Quiz.");
	else
		printf("\t\t\tWelcome Back To The Quiz.");
	printf("\n--------------------------------------------------------------------------------\n");
	if(crash == 0)
	{	
		printf("Enter your name: \n");
		scanf("%s",name);
	}
	else printf("%s please proceed.",name); 
	printf("\n\n");
	if(c_id == -1){
		result_1 = first_1((void*)&first_1_arg, clnt);
		//printf("Result 1 : %d",*result_1);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		FILE *fpw = fopen("ClientId.txt","w");
		fprintf(fpw,"%d %d %s",*result_1,-1,name);
		c_id = *result_1;
		fclose(fpw);
	}
	printf("Your Client ID: %d\n",c_id);
	char c;
	int choice = -1;
	char answ[15];
	do{
		printf("\n");
		//printf("_______________________\n");
		printf("Choose any option: \t\n");
		printf("~~~~~~~~~~~~~~~~~~~~~\n");
		printf("1. Get Question. \t\n");
		printf("2. Ask Score. \t\t\n");
		printf("3. Ask Rank. \t\t\n");
		printf("4. Get Leaderboard. \t\t\n");		
		printf("5. Exit. \t\n");
		if(crash == 1 && lques != - 1)
			choice = 1;
		else
			scanf("%d",&choice);
		switch(choice){
			case 1:
				if(crash == 1) get_ques_1_arg = lques;
				else	get_ques_1_arg = -1;
				result_2 = get_ques_1(&get_ques_1_arg, clnt);
				if (result_2 == (ques *) NULL) { 
					clnt_perror (clnt, "call failed");
				}
				FILE *fpw = fopen("ClientId.txt","w");
				fprintf(fpw,"%d %d %s",c_id,result_2->q_id,name);
				fclose(fpw);
				printf("\n--------------------------------------------------------------------------------\n");
				printf("%s",result_2->ques);
				printf("\n");
				printf("Give Correct Answer: ");
				if(crash == 0 || lques == -1)
					getchar();
				gets(answ); 
				crash = 0;
				check_ans_1_arg.q_id = result_2->q_id;
				check_ans_1_arg.c_id = c_id;
				strcpy(check_ans_1_arg.ans,answ);
				result_3 = check_ans_1(&check_ans_1_arg, clnt);
				if (result_3 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				if(*result_3 == 1)
					printf("Correct Answer!!!!!\n\n");
				else 
					printf("Wrong Answer :(\n\n");
				//scanf("%s",&c);
				FILE *fpwa = fopen("ClientId.txt","w");
				fprintf(fpwa,"%d %d %s",c_id,-1,name);
				fclose(fpwa);
				sleep(1.5);	
				break;
			case 2:
				ask_score_1_arg = c_id;
				result_4 = ask_score_1(&ask_score_1_arg, clnt);
				if (result_4 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("\nYour Score: %d\n",*result_4);
				//scanf("%s",&c);
				break;
			case 3:
				ask_rank_1_arg = c_id;
				result_5 = ask_rank_1(&ask_rank_1_arg, clnt);
				if (result_5 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("\nYour Rank: %d\n",*result_5);
				//scanf("%s",&c);
				break;
			case 4:
				result_6 = get_board_1((void*)&get_board_1_arg, clnt);
				if (result_6 == (board *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("\tLeaderBoard\n\n");
				printf("Rank\tId\tScore\n\n");
				for(int i = 0 ; i < result_6->size; i++){
					printf("%d\t%d\t%d\n",i+1,result_6->id[i],result_6->score[i]);
				}
				printf("\nYour Id: %d",c_id);
				break;				
			case 5:
				exit_1_arg = c_id;
				result_7 = exit_1(&exit_1_arg, clnt);
				if (result_7 == (void *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("\nAu Revoir.\n");
				remove("ClientId.txt");
				break;
			default:
				printf("\nChoose Correct Option.");
				break;
		}		
	}while(choice != 5);
//	assign_1 (host);
	clnt_destroy (clnt);
	exit (0);
}
